# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'latihan6.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(616, 433)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 10, 141, 421))
        self.frame.setStyleSheet("background-color: #3498db;  /* black */\n"
"color: #ffffff;  /* green */\n"
"")
        self.frame.setObjectName("frame")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 121, 101))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_5.setStyleSheet("background-color: #ffffe0;  /* Warna kuning tipis */\n"
"color: #000000;  /* Warna teks hitam */\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 10, 91, 17))
        self.pushButton_10.setMaximumSize(QtCore.QSize(91, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 30, 91, 17))
        self.pushButton_11.setMaximumSize(QtCore.QSize(91, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 50, 91, 17))
        self.pushButton_12.setMaximumSize(QtCore.QSize(91, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 70, 91, 17))
        self.pushButton_13.setMaximumSize(QtCore.QSize(91, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(10, 140, 121, 111))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_6.setStyleSheet("background-color: #ffffe0;  /* Warna kuning tipis */\n"
"color: #000000;  /* Warna teks hitam */\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.checkBox = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox.setGeometry(QtCore.QRect(20, 10, 80, 16))
        self.checkBox.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"\n"
"")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_7.setGeometry(QtCore.QRect(20, 50, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_8.setGeometry(QtCore.QRect(20, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"\n"
"")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_9.setGeometry(QtCore.QRect(20, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"")
        self.checkBox_9.setObjectName("checkBox_9")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(10, 280, 121, 121))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_7.setStyleSheet("background-color: #ffffe0;  /* Warna kuning tipis */\n"
"color: #000000;  /* Warna teks hitam */\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.radioButton = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"\n"
"")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"\n"
"")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"\n"
"")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"\n"
"")
        self.radioButton_5.setObjectName("radioButton_5")
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setGeometry(QtCore.QRect(120, -220, 341, 361))
        self.frame_4.setStyleSheet("background-color: #ffff00;  /* Warna latar kuning */\n"
"color: #000000;  /* Warna teks hitam */\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(170, 10, 361, 421))
        self.frame_2.setStyleSheet("background-color: #3498db;  /* black */\n"
"color: #ffffff;  /* green */\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 341, 31))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_3.setSizeIncrement(QtCore.QSize(300, 0))
        self.frame_3.setBaseSize(QtCore.QSize(0, 0))
        self.frame_3.setStyleSheet("background-color: #ffffff;  /* Warna latar putih */\n"
"color: #000000;  /* Warna teks hitam */\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 80, 17))
        self.pushButton.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 30, 56, 17))
        self.pushButton_2.setStyleSheet("background-color: #ffff00;  /* Warna latar kuning */\n"
"color: #000000;  /* Warna teks hitam */\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 30, 56, 17))
        self.pushButton_3.setStyleSheet("background-color: #ffff00;  /* Warna latar kuning */\n"
"color: #000000;  /* Warna teks hitam */\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 30, 56, 17))
        self.pushButton_4.setStyleSheet("background-color: #ffff00;  /* Warna latar kuning */\n"
"color: #000000;  /* Warna teks hitam */\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 10, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 10, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(130, 30, 56, 17))
        self.pushButton_7.setStyleSheet("background-color: #ffff00;  /* Warna latar kuning */\n"
"color: #000000;  /* Warna teks hitam */\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setGeometry(QtCore.QRect(170, 30, 56, 17))
        self.pushButton_8.setStyleSheet("background-color: #ffff00;  /* Warna latar kuning */\n"
"color: #000000;  /* Warna teks hitam */\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(260, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Putih semi-transparan */\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setGeometry(QtCore.QRect(10, 50, 341, 361))
        self.frame_8.setStyleSheet("background-color: #ffffe0;  /* Warna kuning tipis */\n"
"color: #000000;  /* Warna teks hitam */\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_10.setText(_translate("Form", "PushButton"))
        self.pushButton_11.setText(_translate("Form", "PushButton"))
        self.pushButton_12.setText(_translate("Form", "PushButton"))
        self.pushButton_13.setText(_translate("Form", "PushButton"))
        self.checkBox.setText(_translate("Form", "CheckBox"))
        self.checkBox_3.setText(_translate("Form", "CheckBox"))
        self.checkBox_7.setText(_translate("Form", "CheckBox"))
        self.checkBox_8.setText(_translate("Form", "CheckBox"))
        self.checkBox_9.setText(_translate("Form", "CheckBox"))
        self.radioButton.setText(_translate("Form", "RadioButton"))
        self.radioButton_2.setText(_translate("Form", "RadioButton"))
        self.radioButton_3.setText(_translate("Form", "RadioButton"))
        self.radioButton_4.setText(_translate("Form", "RadioButton"))
        self.radioButton_5.setText(_translate("Form", "RadioButton"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.pushButton_4.setText(_translate("Form", "PushButton"))
        self.pushButton_5.setText(_translate("Form", "PushButton"))
        self.pushButton_6.setText(_translate("Form", "PushButton"))
        self.pushButton_7.setText(_translate("Form", "PushButton"))
        self.pushButton_8.setText(_translate("Form", "PushButton"))
        self.pushButton_9.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
